server_name: ConfiguredMCPServer-YAML
logger_level: debug # Example: different level for YAML
transport:
  type: sse # Example: different transport for YAML
  address: "127.0.0.1:8096"
  sse_path: "/mcp-sse"
  message_path: "/mcp-msg"
tools:
  - name: echo
    description: Simple echo tool (from config)
  - name: ping
    description: Simple ping tool (from config)
