server_name = "ConfiguredMCPServer-TOML"
logger_level = "warn" # Example: different level for TOML

[transport]
type = "stdio" # Example: different transport for TOML
# Stdio has no address/path

[[tools]]
name = "echo"
description = "Simple echo tool (from config)"