# Site settings
title: GoMCP
description: >- # this means to ignore newlines until "baseurl:"
  A Go library for implementing the Model Context Protocol (MCP).
# baseurl: "" # the subpath of your site, e.g. /blog. Leave empty for root.
# url: "https://gomcp.dev" # the base hostname & protocol for your site, e.g. http://example.com

# Remote theme settings
remote_theme: just-the-docs/just-the-docs

# Theme-specific configuration
# Color scheme supports "light", "dark", "dark_high_contrast", "light_high_contrast"
color_scheme: dark
search_enabled: true

# Aux links for header navigation
aux_links:
  "GoMCP on GitHub":
    - "https://github.com/localrivet/gomcp"

# Footer content
footer_content: 'Copyright &copy; 2025 localrivet. Distributed by an <a href="https://github.com/localrivet/gomcp/blob/main/LICENSE">MIT license.</a>'
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
